# Needed to enable user workload monitoring
# https://www.redhat.com/en/blog/custom-metrics-autoscaler-on-openshift
# https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html-single/monitoring/index#enabling-monitoring-for-user-defined-projects_preparing-to-configure-the-monitoring-stack-uwm
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true 
    alertmanagerMain:
      enableUserAlertmanagerConfig: true