apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-load-job
  namespace: demo
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      name: kafka-producer
      labels:
        app: kafka-producer
    spec:
      restartPolicy: Never
      containers:
      - name: kafka-producer
        image: quay.io/zroubalik/kafka-app:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        command: [ "/kafkaproducerapp" ]
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap.demo.svc:9092
          - name: MESSAGE_COUNT
            value: "10"                    # increase this for a bigger load
          - name: DELAY_MS
            value: "100"
          - name: TOPIC
            value: my-topic
          - name: GROUP_ID
            value: my-kafka-consumer-group
